"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Self

__author__ = ...
__copyright__ = ...
__license__ = ...
logger = ...
ANYEVENT_HTTP_STATUS_CODES = ...
SERVICES = ...
def config_failure(message, *args):
    ...

class ResourceException(Exception):
    """
    An Exception thrown when an Proxmox API call failed
    """
    def __init__(self, status_code, status_message, content, errors=..., exit_code=...) -> None:
        """
        Create a new ResourceException

        :param status_code: The HTTP status code (faked by non-HTTP backends)
        :type status_code: int
        :param status_message: HTTP Status code (faked by non-HTTP backends)
        :type status_message: str
        :param content: Extended information on what went wrong
        :type content: str
        :param errors: Any specific errors that were encountered (converted to string), defaults to None
        :type errors: Optional[object], optional
        """
        ...
    


class AuthenticationError(Exception):
    ...


class ProxmoxResource:
    def __init__(self, **kwargs) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getattr__(self, item): # -> ProxmoxResource:
        ...
    
    def url_join(self, base, *args): # -> str:
        ...
    
    def __call__(self, resource_id=...): # -> Self | ProxmoxResource:
        ...
    
    def get(self, *args, **params): # -> None:
        ...
    
    def post(self, *args, **data): # -> None:
        ...
    
    def put(self, *args, **data): # -> None:
        ...
    
    def delete(self, *args, **params): # -> None:
        ...
    
    def create(self, *args, **data): # -> None:
        ...
    
    def set(self, *args, **data): # -> None:
        ...
    


class ProxmoxAPI(ProxmoxResource):
    def __init__(self, host=..., backend=..., service=..., **kwargs) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get_tokens(self): # -> tuple[None, None] | Any:
        """Return the auth and csrf tokens.

        Returns (None, None) if the backend is not https using password authentication.
        """
        ...
    


